#Stage 1 build

FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build -- --configuration production

#Stage 2 Runtime

FROM nginx:alpine

# Create non-root user

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /app/dist/docker-angular-test/browser /usr/share/nginx/html

# Fix permissions
RUN chown -R appuser:appgroup /app

# Switch user
USER appuser

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

