#Stage 1 Build

FROM python:3.12-slim-bookworm AS builder

WORKDIR /app

COPY requirnmnet.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirnmnet.txt

#Stage 2 Runtime

FROM python:3.12-slim-bookworm

WORKDIR /app

# Create non-root user

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /install /usr/local

# Fix permissions
RUN chown -R appuser:appgroup /app

# Switch user
USER appuser

COPY . .

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ]
