# Stage 1 Build

FROM python:3.12-slim-bookworm AS builder

WORKDIR /app

COPY requirnmnet.txt .

RUN pip install --no-cache-dir --prefix=/install -r requirnmnet.txt

# Stage 2 Runtime

FROM  python:3.12-slim-bookworm

WORKDIR /app

COPY --from=builder /install /usr/local

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
