#Stage 1 Build

FROM node:18-alpine AS builder

WORKDIR /app

COPY *.json .

RUN npm install

#Stage 2 Runtime

FROM node:18-alpine

WORKDIR /app

# Create non-root user

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=builder /app/node_modules  ./node_modules 

# Fix permissions
RUN chown -R appuser:appgroup /app

# Switch user
USER appuser

COPY . .

CMD [ "npm", "start" ]