#Stage 1 Build

FROM node:18-alpine AS builder

WORKDIR /app

COPY *.json .

RUN npm install

#Stage 2 Runtime

FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules  ./node_modules 

COPY . .

CMD [ "npm", "start" ]