#Stage 1 Build

FROM  maven:3.9-eclipse-temurin-21 AS builder

WORKDIR /app

COPY pom.xml .

RUN mvn dependency:go-offline

COPY . .

RUN mvn clean package

# Stage 2 Runtime

FROM eclipse-temurin:21-jre

WORKDIR /app

# Create non-root user
RUN groupadd appgroup && useradd -g appgroup appuser

COPY --from=builder /app/target/*.jar  app.jar

# Fix permissions
RUN chown -R appuser:appgroup /app

# Switch user
USER appuser

CMD ["java", "-jar", "app.jar"]
