#-------- Stage 1 : Builder --------

FROM node:18-alpine AS builder
ARG REACT_APP_API_URL=/api
ENV REACT_APP_API_URL=$REACT_APP_API_URL

WORKDIR /app

#Install dependencies and produce the production build
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# -------- Stage 2 : Runtime --------
FROM nginx:alpine AS runtime

# Serve the compiled build from nginx
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
