apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-manager
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-sa   # IRSA — allows reading Secrets Manager
      containers:
        - name: backend
          image: 169976490560.dkr.ecr.us-east-1.amazonaws.com/task-manager:backend03
          ports:
            - containerPort: 8000

          # ---- Env from Kubernetes Secret (synced from AWS Secrets Manager) ----
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secret
                  key: password
            - name: APP_VERSION
              value: "1.0.0"

          # ---- Startup Probe — gives the app 60s to start before liveness begins ----
          startupProbe:
            httpGet:
              path: /api/health/startup
              port: 8000
            failureThreshold: 12
            periodSeconds: 5

          # ---- Liveness Probe — restarts pod if app hangs ----
          livenessProbe:
            httpGet:
              path: /api/health/live
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3

          # ---- Readiness Probe — removes pod from ALB if DB unreachable ----
          readinessProbe:
            httpGet:
              path: /api/health/ready
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: task-manager
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP