apiVersion: v1
kind: ConfigMap
metadata:
  name: task-manager-config-map
data:
  DB_HOST: "database-service"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  DB_USER: "admin"
  REACT_APP_API_URL: "http://192.168.49.2:30007"
  PORT: "4000"
  POSTGRES_USER: admin
  POSTGRES_DB: taskdb