replicas: 1

minimumMasterNodes: 1

esJavaOpts: "-Xms512m -Xmx512m"

resources:
  requests:
    cpu: "200m"
    memory: "1Gi"
  limits:
    cpu: "500m"
    memory: "1Gi"

volumeClaimTemplate:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 5Gi

antiAffinity: "soft"

protocol: http

createCert: false

clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"

esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false