global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'shettysagar272@gmail.com'
  smtp_auth_username: 'shettysagar272@gmail.com'
  smtp_auth_password: 'uryowgzdmonrmbci'

route:
  receiver: gmail-alert

receivers:
- name: gmail-alert
  email_configs:
  - to: 'shettysagar272@gmail.com'
    send_resolved: true